### ISSUE TITLE
Show .i2p websites as secure

### ISSUE THREAD

**Issue by qorg11** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#106]
Hi

.i2p websites are marked as insecure by firefox/icecat/other because they are not HTTPS, but they're secure anyways.

This extension should show .i2p websites as secure (Tor browser does this with .onion sites, even if they're http)

**Comment by eyedeekay** [comment]
You're right of course, but unfortunately I do not believe that this is currently possible to accomplish using *solely* a WebExtension, and reaching down into this part of the browser using some other thing, like a freestanding profile or a native application, is not compatible with the goals of the WebExtension itself, also it comes with a pretty high risk to security when implementing it. If you think about it, it makes sense that manipulating the security notification areas would be a pretty tightly controlled action.

**However** we do have the much easier, much less risky option of adding our *own* secure notification to the "PageAction" area. If you navigate to, for instance, [https://stats.i2p](https://stats.i2p), with the extension you will see a "Toopie" in your Navigation Bar. That indicates that the PageAction is available, clicking it summarizes the properties of the site at that address. The implementation right now is very basic and could readily be expanded. We could, for instance, create a "Padlock" design in multiple colors with an "I2P Logo" theme to place in the "PageAction." A green, closed padlock labeled "I2P" could be used for .i2p domains, and a blue, closed padlock could be used for https://*.i2p domains.

The biggest difference is that instead of the notification being on the left-hand side of the navigation bar, it would be on the right.

**Comment by eyedeekay** [comment]
Added in: https://i2pgit.org/idk/I2P-in-Private-Browsing-Mode-Firefox/-/merge_requests/23
