### ISSUE TITLE
Something like onion-location header

### ISSUE THREAD

**Issue by qorg11** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#109]
Hi.

Tor Browser automatically [redirects to the .onion](https://support.torproject.org/onionservices/onion-location/) site specified in the `onion-location` header.

So I think that this extension should redirect to the I2P website specified in a, for instance, `i2p-location` header

Thanks!

**Comment by eyedeekay** [comment]
We already have this. We don't redirect automatically, that was a conscious decision, but in every other respect we have this feature with the X-I2P-Location header. You'll  see an indicator in the same place that the "lock" shows up for I2P, HTTPS-over-I2P, etc. For redirecting automatically, right now, I think the right way to do it is with an interstitial in the HTTP proxy, so that we're only redirecting people to the .i2p site if they are visiting the clearnet equivalent over an outproxy. Right now ramble and i2pgit are the only services I know of which use this form of the header. idk.i2p also uses the meta http-equiv variant.

**Comment by eyedeekay** [comment]
Turns out there was a small bug in the implementation, which is fixed on the main branch and will be fixed in plugin release as soon as it clear's AMO's queue.
