### ISSUE TITLE
BrowserAction: Text Workflow ( Home Page/ Legwork ) 

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#119]
In this section the "Home Page" links to the Extension Page. But it looks like it should link to the service that is being used to query .i2p sites.

And if i enter a random search topic in the search box, I get to the I2P addressbook where I conclude my journey because that topic is not in an addressbook.

**If there is extra configuration that needs to happen for this workflow, can instruction be included in the Browser is Ready To Use i2P box?** 

_ie "You will need to add the address for Legwork.i2p to your addressbook to use the search feature. The key is is (..........) . Add it here (http://127.0.0.1:7657/dns) ( then advise if refresh is needed or other)._

As for the Home Page Link - will this change to the Legwork link if the above configuration happens?

<img width="386" alt="Screen Shot 2022-09-27 at 4 38 13 PM" src="https://user-images.githubusercontent.com/50714166/192634074-4a2e4ee4-3192-4c14-b6d7-0dbf59d806c4.png">

**Comment by Shoalsteed** [comment]
Text Change:

**Your browser is now configured to access the I2P network**

and add required config here as noted above. 

<img width="254" alt="Screen Shot 2022-09-27 at 4 35 39 PM" src="https://user-images.githubusercontent.com/50714166/192636355-d07c7ca4-8100-40ca-b880-af91b2e6e11d.png">

**Comment by eyedeekay** [comment]
> In this section the "Home Page" links to the Extension Page. But it looks like it should link to the service that is being used to query .i2p sites.

It's there because it needs to go somewhere and I thought it needed to go somewhere near the top. I can move it, but I'm going to have to put it to last because it's layout-not-content. It has no direct relationship to the search other than occupying a nearby space on the same menu.

> 
> And if i enter a random search topic in the search box, I get to the I2P addressbook where I conclude my journey because that topic is not in an addressbook.

This is the thing which is easiest to fix, it just introduces a little more confusion and a little less human-readability. If I refer to legwork as http://cuss2sgthm5wfipnnztrjdvtaczb22hnmr2ohnaqqqz3jf6ubf3a.b32.i2p/ instead of legwork then I can craft the query and send it to the b32 instead of using the human-readable address. People won't know where they're going, but they will get there.

> 
> **If there is extra configuration that needs to happen for this workflow, can instruction be included in the Browser is Ready To Use i2P box?**

Yes it can

> 
> As for the Home Page Link - will this change to the Legwork link if the above configuration happens?

No it will not.

**Comment by Shoalsteed** [comment]
Can "Home Page" be changed to "Legwork Browser" and not have a link?

**Comment by Shoalsteed** [comment]
<img width="460" alt="Screen Shot 2022-09-27 at 5 55 40 PM" src="https://user-images.githubusercontent.com/50714166/192643097-c7aafc58-2aee-438e-be5c-e93bd54e5cea.png">

Could the Home Page link be added here?

**Comment by eyedeekay** [comment]
Yes, checked in locally for testing.

**Comment by eyedeekay** [comment]
If you clone the source, pull the latest, run `make zip` an `i2psetproxy.js.zip` file will be created in the parent directory. Then, on about:addons "Install Add-On from file" to test the changes. It will be unloaded when your browsing session is over.
