### ISSUE TITLE
BrowserAction: Applications Section 

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#121]
1. Since using this extension, I feel like I am always losing my way to /home on my router console. 
That is a me thing maybe, but, I like to see it or access it quickly.

Since this section is about connecting to your I2P Java applications, instead of linking to the home page of the router extension, 
(Help Page) - could this link to /home? 

2. Does this extension only work with I2P Java? if that is the case, should it say so?

In the section where the text says " These applications work with I2P...."
Would it make sense to change this to: **_This extension allows direct access to the following applications in your I2P Java router. To enable this feature, ....do this .....)._**

In the sections for the applications that the extension links too - should the names of the applications be used in the descriptions. 

Email: Access SusiMail, the I2P Network webmail client.

Bittorrent: Access Snark, the anonymizing peer-to-peer file sharing bittorrent application for the I2P network.

<img width="444" alt="Screen Shot 2022-09-27 at 5 26 04 PM" src="https://user-images.githubusercontent.com/50714166/192638958-1beef07a-c89f-4869-80e2-3429cff4e4ae.png">

**Comment by eyedeekay** [comment]
1. I'll add a router console entry to that section but I'd rather not get rid of the extension help page. That's the only place it is accessible from.
2. No it works with any I2P distribution, however, many of it's features work best with I2P Java. For i2pd users, you get basic proxy functionality when you use it with just i2pd, you get bittorrent functionality if you're using Snark Standalone alongside it, and you end up with all the features if you enable I2PControl *and* run Snark Standalone on `localhost:7657`. When using it with i2pd, things which aren't available will almost all automatically blank themselves out.

Re: re-introducing brand names that's fine but just for my own edification can you walk me through the thought-process? I pause because it used to be like that, where `[name](link to app): is a built-in I2P $app_protocol client`.

**Comment by Shoalsteed** [comment]
> 1. I'll add a router console entry to that section but I'd rather not get rid of the extension help page. That's the only place it is accessible from.
> 2. No it works with any I2P distribution, however, many of it's features work best with I2P Java. For i2pd users, you get basic proxy functionality when you use it with just i2pd, you get bittorrent functionality if you're using Snark Standalone alongside it, and you end up with all the features if you enable I2PControl _and_ run Snark Standalone on `localhost:7657`. When using it with i2pd, things which aren't available will almost all automatically blank themselves out.
> 
 Should any instruction for different distributions be mentioned in the onboarding for the extension homepage?

> Re: re-introducing brand names that's fine but just for my own edification can you walk me through the thought-process? I pause because it used to be like that, where `[name](link to app): is a built-in I2P $app_protocol client`.

My though was familiarity - so if a person is used to using Snark, they should see that in the bittorrent reference that  is what we are talking about and where they are going if they click a link.

**Comment by Shoalsteed** [comment]
**Applications**
The I2P router console and applications open in their own tab, providing them with the same security benefits as browsing with this extension. Email, file sharing, and any other I2P applications are isolated from your browsing and from each other.


**Toopie**
View your router connection status, restart or stop your router as well. 

**Router Console**
Access your I2P router console and its full range of applications and configurations.

**Hidden Services Manager**
View status messages, service and tunnel configuration.

**Email**
Quick access to the SusiMail I2P network email client. 

**BitTorrent** 
Quick access to Snark, the Peer-to-peer I2P network specific file sharing application.
