### ISSUE TITLE
Extension Page: Content (Top Section) 

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#122]
Top Section

In this section , the onboarding needs to be changed. It incorrectly suggests that the browser is for accessing the internet. 
Additionally, information about application access in redundant, and the onboarding should focus on using the extension, not introducing users to I2P.

Before:
<img width="982" alt="Screen Shot 2022-09-28 at 10 00 52 AM" src="https://user-images.githubusercontent.com/50714166/192799205-a7ae76a2-636c-4d39-8ea5-ef99d210e7a2.png">

Mock up with suggested changes: ( ignore colour!) 
<img width="959" alt="Screen Shot 2022-09-28 at 10 01 58 AM" src="https://user-images.githubusercontent.com/50714166/192800026-d3c27345-7f18-4d40-8976-eb40aa2c6640.png">

**Comment by eyedeekay** [comment]
> It incorrectly suggests that the browser is for accessing the internet.

It says no such thing. It says "Your browser is set up to use I2P" which is true, and that the "Proxy is ready" which is also true. Even if the proxy wasn't ready and I2P wasn't even installed, your browser would still be set up to use I2P. Setting up I2P and setting up a browser to use it are separate processes everywhere except the Easy-Install bundle for Windows. If you couldn't browser the clearnet directly in clearnet tabs the extension would be broken.

If you mean outproxy use, then there are 2 big problems with that, both related to the separation of the I2P Setup and the Browser Setup processes. I2PIPB cannot assume an outproxy is present at all because it has no insight into the user's configuration or intent:

1. The only way I could do this is by scraping the information out of the router console page. It would be brittle, it would not be cross-platform, and it would work with only specific versions of specific routers.
2. The second problem is that even if it could assume that, it would not be possible for the extension to know the **user's intent** when they open a clearnet website. It is intentionally not a whole-browser solution, it's a container-tab solution.

As far as I can tell, automatic configuration of browsing with an outproxy for clearnet sites is not only out of scope it's actually impossible. If that's the case, then I believe textual changes in 66f56b4375b8361b62d3898b3c596f34316be208 and 66f56b4375b8361b62d3898b3c596f34316be208 reflect a way to make the act of opening an I2P tab more obvious.

If it's a whole-browser solution we need then that's what https://github.com/eyedeekay/i2p.plugins.firefox does.

**Comment by Shoalsteed** [comment]
This is the section I am referencing: 
It mentions the internet: 

<img width="417" alt="Screen Shot 2022-09-30 at 3 57 19 PM" src="https://user-images.githubusercontent.com/50714166/193347026-fae4dd40-e244-4089-9eab-0f628e030934.png">

**Comment by eyedeekay** [comment]
OK that makes a little more sense. I still don't know how to delineate it properly, though. It *will* do all those things, in I2P tabs, which is what it's for. So the verbiage needs to change to reflect that.

**Comment by Shoalsteed** [comment]
Probably saying something along the lines of "this extension works with your current outproxy configuration and will not interfere with its function. It will isolate these actions in its own container as it does I2P network traffic and when you use an I2P application"

**Comment by eyedeekay** [comment]
How about "This extension works automatically when you are browsing I2P sites. If you want to use I2P as a proxy to clearnet sites, use the `I2P In Private Browsing` button in the toolbar and click `New I2P Browser Tab` to switch to I2P Browsing in a new tab."

**Comment by Shoalsteed** [comment]
If a person is not using the Windows easy installer, has not set up anything already to use the existing outproxy, is this instruction still true? Would opening the new I2P browser tab work in this way?

**Comment by eyedeekay** [comment]
Yes, no matter what distribution of I2P they're using at this time they do have an outproxy, which is normally going to be `exit.stormycloud.i2p`. There is no extension-side configuration necessary to use an outproxy, other than switching to an I2P tab.
