### ISSUE TITLE
Browser- File - New Container Tab 

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#126]
Trying to access the console or mail from this tab takes me to the Extension home page.
However , if I choose the I2P Browser, it does open a functional tab and I can get to an I2P site.
<img width="211" alt="Screen Shot 2022-09-28 at 2 32 10 PM" src="https://user-images.githubusercontent.com/50714166/192861887-1b8477b6-30e6-47cb-a596-6774a7a9ff89.png">
<img width="323" alt="Screen Shot 2022-09-28 at 2 34 45 PM" src="https://user-images.githubusercontent.com/50714166/192861888-e6811962-909b-469c-b99a-fee412494354.png">
<img width="471" alt="Screen Shot 2022-09-28 at 10 39 10 AM" src="https://user-images.githubusercontent.com/50714166/192861890-28a32c91-b3af-4074-9cd2-33412473b0a4.png">

**Comment by eyedeekay** [comment]
I cant change this, container tabs can't set individual homepages. The closest I can get is to override them with the extension homepage. I might be able to figure out some kind of workaround but this one might need to be a wontfix

**Comment by Shoalsteed** [comment]
Just so I understand: none of these ( ( Dispatch, MuWire, Etc) have any linking functionality?

**Comment by eyedeekay** [comment]
They can be forced into the internal extension page but the user needs to click the respective link on the extension page to reach the application. I might be able to work around it by redirecting but I don't know if I can reliably tell that it's the first time they've opened the tab. Could end up with situations that spam a bunch of tabs because it keeps trying to re-isolate.

**Comment by Shoalsteed** [comment]
Since these redirect to the home page , then maybe just have a note in the applications section with email, hidden services, and snark that any applications that are available in your console will open in a container ?

**Comment by eyedeekay** [comment]
Ok sure. However, the rule for containerizing in this plugin is that if it's not happening automatically, then it's broken and the real problem is that. They shouldn't, and as far as I know, aren't, able to approach any console page, application, or I2P site from a path where the automatic isolation isn't triggered, in fact the entire UI is just different ways of triggering the automatic isolation function. This workaround is only necessary when triggering it from Mozilla's container-tab UI, and not from the browserAction menu or any of the myriad ways of automatically triggering the isolator, and it doesn't actually require them to read the warning to work correctly.

**Comment by Shoalsteed** [comment]
> Ok sure. However, the rule for containerizing in this plugin is that if it's not happening automatically, then it's broken and the real problem is that. They shouldn't, and as far as I know, aren't, able to approach any console page, application, or I2P site from a path where the automatic isolation isn't triggered, in fact the entire UI is just different ways of triggering the automatic isolation function. This workaround is only necessary when triggering it from Mozilla's container-tab UI, and not from the browserAction menu or any of the myriad ways of automatically triggering the isolator, and it doesn't actually require them to read the warning to work correctly, and not because the normal isolator isn't working, just because there can only be one homepage.

Yes, this sounds like the workaround.

**Comment by eyedeekay** [comment]
Current screenshot of the page they get redirected to if they open a tab from the `File` menu

![current](https://user-images.githubusercontent.com/8733713/193477600-bc40a4ec-8730-44c8-889c-de7ff4990a7d.png)

**Comment by Shoalsteed** [comment]
Should this issue be closed?

**Comment by eyedeekay** [comment]
Yes I think so
