### ISSUE TITLE
Option to disable in normal windows

### ISSUE THREAD

**Issue by 5HT2** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#133]
I'd like to be able to leave this extension enabled in *only* private browsing, as when I re-enable it, it refreshes all my tabs and for some reason un-associates cookies from them temporarily? Meaning, I either have to sign back into my sites, or disable the extension and manually refresh all the tabs I had opened

Alternatively, one of these would be great:
- Don't refresh all opened tabs when enabling
- Fix the cookie association issue? I don't know if it's feasible I'm not sure why it happens

**Comment by eyedeekay** [comment]
Unfortunately not, both of those phenomena are actually Mozilla-related and not me-related. It happens when you load or unload an extension that changes cookie settings. When the extension is disabled, the cookie settings are restored to whatever they were before it was installed. When it's re-enabled, stricter rules are once again applied and everything gets refreshed.

The best way to work around this that I know of is to put the extension into it's own profile and launch that profile with a wrapper script, i.e. a directory structure like this:

```sh
./i2p-profile-dir/user.js
./i2p-profile-dir/extensions/i2ppb@eyedeekay.github.io.xpi
```

and a launcher like:

```sh
#! /usr/bin/env sh
firefox --profile ./i2p-profile-dir --private-window $@
```

That will prevent the extension from being used in a regular profile and automatically launch you into a private window. **BUT** you'll also need to add at least:

```javascript
user_pref("extensions.allowPrivateBrowsingByDefault", true);
user_pref("extensions.PrivateBrowsing.notification", false);
```

To the `user.js` to enable the extension to be loaded on the first run.

The good news is that if you want it to be, that elaboration can all be moot. I needed such a wrapper on several occasions and have 2 really excellent versions of it, one in Java and one in Go, both of which will do all of the above for you:

- https://github.com/eyedeekay/i2p.plugins.firefox/releases
- https://github.com/eyedeekay/go-i2pbrowser

Both of these will isolate I2P Browsing to a single profile, thereby containing the extension and preventing the problem where disabling and re-enabling it on your main profile will log you out of web sites.

**Comment by 5HT2** [comment]
Okay! That solution is more than fantastic, thank you for the reply :)
