### ISSUE TITLE
Does this extension compatible with i2pd ?

### ISSUE THREAD

**Issue by Nokia808** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#39]
Hi. There is C++ correspondence for i2p original java application, called i2pd - see:
https://i2pd.website/
https://github.com/PurpleI2P/i2pd

My question is that: does this extension compatible with i2pd or it is only working with i2p ?

**Comment by eyedeekay** [comment]
Yes for all intents and purposes it works with i2pd just fine, but since i2pd doesn't have built-in torrent clients, e-mail clients, etc, some of the features won't be used. The core behavior of "I2P in Private Browsing" will work, and the "Router Console" contextual identity will work, but there isn't a protocol handler for XD or BiglyBT integration yet and it's not compatible with say, Thunderbird, so it's not a solution for e-mail over i2pd yet. Also for now it blocks access to non-i2p services on the localhost, so you won't be able to administer XD using a a browser with this plugin installed for now. For Private Browsing and Router Console Administration it will work fine though.

**Comment by eyedeekay** [comment]
If you have no other questions, I am going to close this.
